name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Gradle build
      id: gradle-build
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Gradle build
        setup-command: ''
        command: gradle jar
        timeout: 5
        max-score: 0
    - name: Copy client JAR
      id: copy-client-jar
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Copy client JAR
        setup-command: ''
        command: cp Client/build/libs/Client-5785.jar .
        timeout: 1
    - name: Copy server JAR
      id: copy-server-jar
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Copy server JAR
        setup-command: ''
        command: cp Router/build/libs/Router-5785.jar .
        timeout: 1
    - name: Build Multiclient tester
      id: build-multiclient-tester
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Build Multiclient tester
        setup-command: ''
        command: gcc -o MultiClient MultiClient.c
        timeout: 1
    - name: Run test script
      id: run-test-script
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Run test script
        setup-command: chmod 700 router-test-script
        command: "./router-test-script"
        timeout: 10
    - name: Client Test1
      id: client-test1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Client Test1
        setup-command: ''
        command: cat outfiles/test1-client-output.txt
        input: ''
        expected-output: Connected to router\s+21.0.58.150\s+->\s+R1\s+21.0.58.1\s+->\s+R2\s+21.0.57.200\s+->\s+R3\s+21.0.49.6\s+->\s+R4\s+21.0.40.8\s+->\s+R5\s+21.0.58.150\s+->\s+R1\s+22.100.144.55\s+not
          found
        comparison-method: regex
        timeout: 1
        max-score: 2
    - name: Client Test2
      id: client-test2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Client Test2
        setup-command: ''
        command: cat outfiles/test2-client-output.txt
        input: ''
        expected-output: Connected to router\s+21.126.128.5\s+->\s+R5\s+85.249.95.171\s+not
          found\s+159.129.120.134\s+not found\s+148.240.87.240\s+not found\s+13.133.56.218\s+not
          found
        comparison-method: regex
        timeout: 1
        max-score: 2
    - name: Client Test3
      id: client-test3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Client Test3
        setup-command: ''
        command: cat outfiles/test3-client-output.txt
        input: ''
        expected-output: Connected to router\s+205.181.189.90\s+not found\s+176.29.92.149\s+not
          found\s+81.212.167.197\s+not found\s+150.224.181.232\s+not found\s+21.12.33.113\s+->\s+R5\s+52.138.121.125\s+not
          found\s+21.64.59.209\s+->\s+R5\s+133.126.27.255\s+not found\s+56.67.13.81\s+not
          found\s+21.154.101.150\s+not found
        comparison-method: regex
        timeout: 1
        max-score: 2
    - name: Client Test4
      id: client-test4
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Client Test4
        setup-command: ''
        command: cat outfiles/test4-client-output.txt
        input: ''
        expected-output: 'Connected to router\s+21.100.25.12\s+->\s+R5\s+21.5.2\s+->\s+Illegal
          address: 21.5.2'
        comparison-method: regex
        timeout: 1
        max-score: 2
    - name: Client Test5
      id: client-test5
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Client Test5
        setup-command: ''
        command: cat outfiles/test5-client-output.txt
        input: ''
        expected-output: Connected to router\s+85.249.95.171\s+->\s+R45\s+159.129.120.134\s+->\s+R30\s+2.50.25.12
          not found\s+148.240.87.240\s+->\s+R9\s+13.133.56.218\s+->\s+R17\s+74.186.187.75\s+->\s+R65
        comparison-method: regex
        timeout: 1
        max-score: 2
    - name: Client Test6
      id: client-test6
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Client Test6
        setup-command: ''
        command: cat outfiles/test6-client-output.txt
        input: ''
        expected-output: Connected to router\s+2.27.193.114 not found\s+6.8.97.45\s+->\s+R24\s+118.138.154.79\s+->\s+R5
        comparison-method: regex
        timeout: 1
        max-score: 2
    - name: Client Test7
      id: client-test7
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Client Test7
        setup-command: ''
        command: cat outfiles/test7-client-output.txt
        input: ''
        expected-output: Connected to router\s+59.79.130.93\s+->\s+R15\s+121.227.252.126\s+->\s+R16\s+2.12.22.22\s+not
          found\s+197.168.47.14\s+->\s+R51\s+197.168.47.13\s+->\s+R51
        comparison-method: regex
        timeout: 1
        max-score: 2
    - name: Client Test8
      id: client-test8
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Client Test8
        setup-command: ''
        command: cat outfiles/test8-client-output.txt
        input: ''
        expected-output: 'Connected to router\s+205.181.189.90\s+->\s+R4\s+176.29.92.149\s+->\s+R10\s+81.212.167.197\s+->\s+R8\s+1.1.1\s+->\s+Illegal
          address: 1.1.1\s+150.224.181.232\s+->\s+R9\s+89.12.33.113\s+->\s+R22\s+52.138.121.125\s+->\s+R40\s+58.64.59.209\s+->\s+R52\s+23.126.27.255\s+->\s+R11\s+56.67.13.81\s+->\s+R76\s+105.154.101.150\s+->\s+R27'
        comparison-method: regex
        timeout: 1
        max-score: 2
    - name: Client Test9
      id: client-test9
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Client Test9
        setup-command: ''
        command: cat outfiles/test9-client-output.txt
        input: ''
        expected-output: Connected to router\s+68.189.142.23\s+->\s+R23\s+190.179.212.203\s+->\s+R35\s+17.70.51.141\s+->\s+R11\s+9.255.108.148\s+->\s+R17\s+189.160.222.218\s+->\s+R37\s+196.81.140.48\s+->\s+R34\s+1.210.190.23\s+not
          found\s+218.18.55.31\s+->\s+R43\s+48.199.220.76\s+->\s+R6\s+220.27.167.223\s+->\s+R29\s+110.80.10.153\s+->\s+R1\s+90.98.72.196\s+->\s+R22\s+43.96.28.233\s+->\s+R14\s+195.213.11.44\s+->\s+R4\s+67.57.128.177\s+->\s+R23\s+99.207.130.137\s+->\s+R1\s+37.6.69.115\s+->\s+R32\s+8.168.165.181\s+->\s+R17\s+159.136.68.67\s+->\s+R30\s+47.176.108.153\s+->\s+R14\s+77.92.255.57\s+->\s+R19
        comparison-method: regex
        timeout: 1
        max-score: 2
    - name: Client Test10
      id: client-test10
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Client Test10
        setup-command: ''
        command: cat outfiles/test10-client-output.txt
        input: ''
        expected-output: 'Socket 1 Response: 85.249.95.171\s+->\s+R45\s+Socket 2 Response:
          85.249.95.171\s+->\s+R45\s+Socket 3 Response: 59.79.130.93\s+->\s+R15\s+Socket
          1 Response: 159.129.120.134\s+->\s+R30\s+Socket 2 Response: 159.129.120.134\s+->\s+R30\s+Socket
          3 Response: 1.23.23.0\s+->\s+NotFound\s+Socket 1 Response: 6.9.22.9\s+->\s+R24\s+Socket
          2 Response: 148.240.87.240\s+->\s+R9\s+Socket 3 Response: 121.227.252.126\s+->\s+R16\s+Socket
          1 Response: 22.23.3.2\s+->\s+R11\s+Socket 2 Response: 2.33.56.218\s+->\s+NotFound\s+Socket
          3 Response: 197.168.47.13\s+->\s+R51\s+Socket 1 Response: 1.1.1\s+->\s+Illegal
          address: 1.1.1\s+Socket 2 Response: 74.186.187.75\s+->\s+R65\s+Socket 1
          Response: 148.240.87.240\s+->\s+R9\s+Socket 2 Response: 21.5.10.6\s+->\s+R11\s+Socket
          1 Response: 13.133.56.218\s+->\s+R17\s+Socket 1 Response: 74.186.187.75\s+->\s+R65'
        comparison-method: regex
        timeout: 1
        max-score: 10
    - name: Client Test17
      id: client-test17
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Client Test17
        setup-command: ''
        command: cat outfiles/test17-client-output.txt
        input: ''
        expected-output: 'Error missing parameter\s+Usage: Client-5785 -dest=ip -port=p
          -addresses=adds'
        comparison-method: regex
        timeout: 1
        max-score: 1
    - name: Client Test18
      id: client-test18
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Client Test18
        setup-command: ''
        command: cat outfiles/test18-client-output.txt
        input: ''
        expected-output: 'Error missing parameter\s+Usage: Client-5785 -dest=ip -port=p
          -addresses=adds\'
        comparison-method: regex
        timeout: 1
        max-score: 1
    - name: Client Test19
      id: client-test19
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Client Test19
        setup-command: ''
        command: cat outfiles/test19-client-output.txt
        input: ''
        expected-output: 'Error missing parameter\s+Usage: Client-5785 -dest=ip -port=p
          -addresses=adds'
        comparison-method: regex
        timeout: 1
        max-score: 1
    - name: Client Test20
      id: client-test20
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Client Test20
        setup-command: ''
        command: cat outfiles/test20-client-output.txt
        input: ''
        expected-output: 'Error: Illegal IP address: abcdef:'
        comparison-method: contains
        timeout: 1
        max-score: 1
    - name: Client Test21
      id: client-test21
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Client Test21
        setup-command: ''
        command: cat outfiles/test21-client-output.txt
        input: ''
        expected-output: 'Error: Illegal port number: For input string: "cats"\s+Usage:
          Client-5785 -dest=ip -port=p -addresses=adds'
        comparison-method: regex
        timeout: 1
        max-score: 1
    - name: Client Test22
      id: client-test22
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Client Test22
        setup-command: ''
        command: cat outfiles/test22-client-output.txt
        input: ''
        expected-output: 'Error communicating: Connection refused'
        comparison-method: contains
        timeout: 1
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        GRADLE-BUILD_RESULTS: "${{steps.gradle-build.outputs.result}}"
        COPY-CLIENT-JAR_RESULTS: "${{steps.copy-client-jar.outputs.result}}"
        COPY-SERVER-JAR_RESULTS: "${{steps.copy-server-jar.outputs.result}}"
        BUILD-MULTICLIENT-TESTER_RESULTS: "${{steps.build-multiclient-tester.outputs.result}}"
        RUN-TEST-SCRIPT_RESULTS: "${{steps.run-test-script.outputs.result}}"
        CLIENT-TEST1_RESULTS: "${{steps.client-test1.outputs.result}}"
        CLIENT-TEST2_RESULTS: "${{steps.client-test2.outputs.result}}"
        CLIENT-TEST3_RESULTS: "${{steps.client-test3.outputs.result}}"
        CLIENT-TEST4_RESULTS: "${{steps.client-test4.outputs.result}}"
        CLIENT-TEST5_RESULTS: "${{steps.client-test5.outputs.result}}"
        CLIENT-TEST6_RESULTS: "${{steps.client-test6.outputs.result}}"
        CLIENT-TEST7_RESULTS: "${{steps.client-test7.outputs.result}}"
        CLIENT-TEST8_RESULTS: "${{steps.client-test8.outputs.result}}"
        CLIENT-TEST9_RESULTS: "${{steps.client-test9.outputs.result}}"
        CLIENT-TEST10_RESULTS: "${{steps.client-test10.outputs.result}}"
        CLIENT-TEST17_RESULTS: "${{steps.client-test17.outputs.result}}"
        CLIENT-TEST18_RESULTS: "${{steps.client-test18.outputs.result}}"
        CLIENT-TEST19_RESULTS: "${{steps.client-test19.outputs.result}}"
        CLIENT-TEST20_RESULTS: "${{steps.client-test20.outputs.result}}"
        CLIENT-TEST21_RESULTS: "${{steps.client-test21.outputs.result}}"
        CLIENT-TEST22_RESULTS: "${{steps.client-test22.outputs.result}}"
      with:
        runners: gradle-build,copy-client-jar,copy-server-jar,build-multiclient-tester,run-test-script,client-test1,client-test2,client-test3,client-test4,client-test5,client-test6,client-test7,client-test8,client-test9,client-test10,client-test17,client-test18,client-test19,client-test20,client-test21,client-test22
